# Generated by Django 6.0.2 on 2026-02-16 20:54

import api.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('slug', models.SlugField(default=uuid.uuid1)),
                ('nom', models.CharField(blank=True, max_length=1000, null=True)),
                ('token', models.CharField(blank=True, max_length=1000, null=True)),
                ('tokens', models.JSONField(blank=True, default=list)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('prenom', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=30, unique=True)),
                ('adresse', models.CharField(max_length=255, null=True)),
                ('pays', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_archive', models.BooleanField(default=False)),
                ('deletion_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('deletion_type', models.CharField(blank=True, choices=[('admin', 'admin'), ('superadmin', 'superadmin'), ('VENDEUR', 'VENDEUR'), ('ACHETEUR', 'ACHETEUR'), ('DELETED', 'DELETED')], max_length=50, null=True)),
                ('user_type', models.CharField(choices=[('admin', 'admin'), ('superadmin', 'superadmin'), ('VENDEUR', 'VENDEUR'), ('ACHETEUR', 'ACHETEUR'), ('DELETED', 'DELETED')], max_length=50)),
                ('deleted_by_cascade', models.CharField(blank=True, max_length=1000, null=True)),
                ('register_by_social_media', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('admin_type', models.CharField(choices=[('admin', 'admin'), ('superadmin', 'superadmin')], default='admin', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('api.user',),
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nom_de_la_boutique', models.CharField(max_length=200)),
                ('domaine', models.CharField(blank=True, max_length=200, null=True)),
                ('devise', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD'), ('XOF', 'XOF')], default='XOF', max_length=20)),
            ],
            options={
                'verbose_name': 'Vendeur',
                'verbose_name_plural': 'Vendeurs',
                'ordering': ('-created_at',),
            },
            bases=('api.user',),
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
    ]
