# Generated by Django 6.0.1 on 2026-03-03 14:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/article')),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1, editable=False)),
                ('titre', models.CharField(blank=True, max_length=20, null=True)),
                ('taux', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendeur')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.FileField(blank=True, null=True, upload_to='uploads/categori')),
                ('is_archived', models.BooleanField(default=False)),
                ('vendeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vendeur')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.promotion')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1)),
                ('nom', models.CharField(blank=True, max_length=150, null=True)),
                ('images', models.FileField(blank=True, null=True, upload_to='uploads/souscategorie')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categorie', to='api.categorie')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.promotion')),
                ('souscategorie', models.ManyToManyField(blank=True, related_name='scategorie', to='api.souscategorie')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=50)),
                ('type', models.CharField(choices=[('taille_unique', 'taille_unique'), ('taille_variable', 'taille_variable'), ('taille_unique_avec_couleur', 'taille_unique_avec_couleur')], max_length=100)),
                ('seuil', models.IntegerField(blank=True, default=0, null=True)),
                ('est_en_avant', models.BooleanField(default=False)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cout_de_revient', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('prix_avec_promo', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit', to='api.categorie')),
                ('images', models.ManyToManyField(blank=True, default=[], to='api.image')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vendeur')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion', to='api.promotion')),
                ('sous_categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.souscategorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1)),
                ('taille', models.CharField(blank=True, max_length=20, null=True)),
                ('couleur', models.CharField(max_length=50, null=True)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('seuil', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(blank=True, default=[], to='api.image')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='api.produit')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='variations',
            field=models.ManyToManyField(blank=True, default=[], related_name='produits', to='api.variation'),
        ),
    ]
