# Generated by Django 6.0.2 on 2026-03-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_categorie_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='sous_categorie',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='images',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_en_avant',
        ),
        migrations.DeleteModel(
            name='SousCategorie',
        ),
    ]
