# Generated by Django 6.0.2 on 2026-03-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_produit_sous_categorie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='promotion',
        ),
    ]
