# Generated by Django 6.0.1 on 2026-04-02 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1)),
                ('reference', models.CharField(max_length=100)),
                ('client_nom', models.CharField(max_length=500)),
                ('client_telephone', models.CharField(max_length=50)),
                ('total_general', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='api.vendeur')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
                'unique_together': {('vendeur', 'reference')},
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=50)),
                ('designation', models.CharField(max_length=500)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=50)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=50)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='api.facture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'ordering': ['id'],
            },
        ),
    ]
