# Generated by Django 6.0.1 on 2026-04-02 15:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_facture_ligne_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(default=api.models._date_aujourdhui),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_facture',
            field=models.DateField(default=api.models._date_aujourdhui),
        ),
        migrations.AddField(
            model_name='facture',
            name='facture_pdf',
            field=models.FileField(blank=True, null=True, upload_to='factures/pdfs/'),
        ),
        migrations.AddField(
            model_name='facture',
            name='paid_statut',
            field=models.CharField(choices=[('payée', 'payée'), ('non payée', 'non payée'), ('partiellement payée', 'partiellement payée')], default='non payée', max_length=40),
        ),
        migrations.AddField(
            model_name='facture',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
