# Generated by Django 6.0.1 on 2026-04-07 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_facture_easymarket_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1)),
                ('nom', models.CharField(max_length=120)),
                ('type_service', models.CharField(choices=[('EMAIL', 'EMAIL'), ('SMS', 'SMS'), ('AUTRE', 'AUTRE')], default='EMAIL', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='categorie',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='uploads/categori'),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='add_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='add_seller',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='best_seller',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='cost_premium',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='couleur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='intech_api_key',
            field=models.CharField(blank=True, default='554ACA96-F050-442D-8E29-BEE77FAE821A', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='nb_vendeur_a_ajouter',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='paygate_api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='paygate_is_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='stock_management',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='stripe_endpoint_secret',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='stripe_is_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='wave_api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='wave_api_secret_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='wave_is_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendeur_service', to='api.service'),
        ),
    ]
