# Generated by Django 6.0.2 on 2026-04-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_service_and_vendeur_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendeur',
            name='add_order',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='add_seller',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='best_seller',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='cost_premium',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='intech_api_key',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='paygate_api_key',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='paygate_is_set',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='service',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='stock_management',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='stripe_endpoint_secret',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='stripe_is_set',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='stripe_publishable_key',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='stripe_secret_key',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='wave_api_key',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='wave_api_secret_key',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='wave_is_set',
        ),
    ]
