# Generated by Django 6.0.1 on 2026-04-09 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_vendeur_add_order_remove_vendeur_add_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendeur_service', to='api.service'),
        ),
    ]
